### PR TITLE
Re-brand with new design and logo.

### PR DESCRIPTION
**Pull request by knightss27**
Figma: https://www.figma.com/file/x48fdS5rtSID8QoRGXYHeE/Fosshost-NEW
(We need to do a mobile version of the design.)

Pages to do (for now):
- [x] Splash
- [x] About
- [x] News
- [x] Blog Post
- [x] Donate
- [x] Apply
- [x] General Static Page

### CODE REVIEW

**Comment by brunomiguel** [comment]
Some suggestions:
- the sponsors name should be aligned to the left in the _about_ page for easier reading
- maybe use a shade of gray on some of the borders so it doesn't seem _heavy_

**Comment by GrahamSH-LLK** [comment]
It looks like you accidentally broke the Sponsors link in the footer by removing the id from the about page.

**Comment by knightss27** [comment]
Good catch, I can fix that.

**Comment by andrewnyr** [comment]
Seth, I love the new site. My only recommendation is that we change Fastly.net to Fastly.com on the sponsors page as that is their primary domain which the .net redirects to anyways.

**Pull request merged**
