### PR TITLE
fixes: added twitter large image meta, so image looks big in discord

### PR DESCRIPTION
**Pull request by sayantan300**
embed. removed "powered by express" because express docs say to remove
it in production.

### CODE REVIEW

**Comment by sayantan300** [comment]
Btw thanks for creating this awesome project! Ps: I used git cli for the first time to make a pull request :)

**Comment by hamptonmoore** [comment]
Hey, mostly lgtm but you completely reformatted the styling in src/server.ts. Can you fix that and force push the change?

**Comment by sayantan300** [comment]
@hamptonmoore hey sry about being late, but eslint and prettier did the format... I don't see how to fix that 😔. Lemme check up for fixes

**Comment by knightss27** [comment]
@sayantan300 Don't worry, I am gonna merge anyways, the formatting doesn't matter that much.

**Comment by sayantan300** [comment]
It looks like you don't have a config for eslint and prettier in the root of the repo. Mind adding it please?

**Comment by sayantan300** [comment]
Alternatively you can cut and paste the changes I did in the main branch manually if you don't have any config for the repo. I hope I didn't change a lot lol

**Comment by sayantan300** [comment]
> @sayantan300 Don't worry, I am gonna merge anyways, the formatting doesn't matter that much.

Ah ok

**Pull request merged**
