### PR TITLE
Add Vignette quote

### PR DESCRIPTION
**Pull request by iojcde**
Add Ayane's quote for Vignette.

### CODE REVIEW

**Comment by GrahamSH-LLK** [comment]
Does this look good? It's a simple console hack, no actual code. 
image

**Comment by knightss27** [comment]
Could also do something like this? Not sure if it looks better or not.
image

**Comment by JcdeA** [comment]
What about a layout like this for desktop, and reducing the padding a bit for mobile?

**Comment by GrahamSH-LLK** [comment]
On mobile it would be nice if they went 1 by one again, that layout would be weird on mobile.

**Comment by JcdeA** [comment]
> On mobile it would be nice if they went 1 by one again, that layout would be weird on mobile.

Yep, that's what I meant.

**Comment by sr229** [comment]
Would probably be better if this was a chat bubble of sorts, or cards you can scroll vertically, something like Stripe and co does.

**Pull request closed without merging**
